# Codemagic configuration for MebelPlace iOS App Store build and Android APK
# This file configures automatic building and uploading to App Store Connect

workflows:
  mebelplace-android:
    name: MebelPlace Android APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      groups:
        - Grand
      vars:
        FLUTTER_VERSION: stable
      
    scripts:
      - name: Set up Flutter
        script: |
          flutter sdk install $FLUTTER_VERSION
          
      - name: Get Flutter packages
        script: |
          cd mebelplace_demo
          flutter packages pub get
          
      - name: Flutter analyze
        script: |
          cd mebelplace_demo
          flutter analyze --no-fatal-infos
          
      - name: Build APK
        script: |
          cd mebelplace_demo
          flutter build apk --release \
            --build-name=1.0.0 \
            --build-number=1
            
    artifacts:
      - mebelplace_demo/build/app/outputs/flutter-apk/*.apk
      
    publishing:
      email:
        recipients:
          - bekaron.company@gmail.com
        notify:
          success: true
          failure: true
  
  mebelplace-ios:
    name: MebelPlace iOS App Store
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - Grand
      vars:
        FLUTTER_VERSION: stable
        BUNDLE_ID: "com.mebelplace.mebelplaceDemo"
        APP_STORE_CONNECT_ISSUER_ID: "94ce68e4-bd5a-4bf4-b266-46f0b9bd0596"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "7R2G5C786A"
      xcode: latest
      cocoapods: default
      
    integrations:
      app_store_connect: mebelplace-integration
      
    scripts:
      - name: Set up code signing
        script: |
          echo "========================================="
          echo "🔧 Creating certificate from existing key"
          echo "========================================="
          
          # Initialize keychain
          keychain initialize
          
          # Get keychain path
          KEYCHAIN_PATH=$(security default-keychain | tr -d '" ' | xargs)
          echo "Keychain: $KEYCHAIN_PATH"
          
          # First, create NEW certificate using our CSR
          echo "Creating new Distribution certificate..."
          app-store-connect certificates create \
            --certificate-type IOS_DISTRIBUTION \
            --csr-file $CM_BUILD_DIR/mebelplace_demo/ios/mycsr.csr \
            --save
          
          # This will download the new .cer file
          # Now convert .cer + .key to .p12 ON MACOS
          echo "Converting to .p12..."
          cd $CM_BUILD_DIR/mebelplace_demo/ios
          
          # Convert .cer to .pem
          openssl x509 -in *.cer -inform DER -out cert.pem -outform PEM
          
          # Create .p12 from .pem + .key
          openssl pkcs12 -export \
            -out distribution.p12 \
            -inkey mykey.key \
            -in cert.pem \
            -passout pass:mebelplace123
          
          # Import to keychain
          echo "Importing certificate..."
          security import distribution.p12 \
            -P mebelplace123 \
            -T /usr/bin/codesign \
            -T /usr/bin/security \
            -k "$KEYCHAIN_PATH"
          
          # Unlock and allow access
          security unlock-keychain -p "" "$KEYCHAIN_PATH"
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" "$KEYCHAIN_PATH"
          
          # Verify
          echo "Verifying certificate..."
          security find-identity -v -p codesigning "$KEYCHAIN_PATH"
          
          # Create provisioning profile
          echo "Creating provisioning profile..."
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE
          
          echo "✅ Signing configured!"
            
          
      - name: Set up Flutter
        script: |
          flutter sdk install $FLUTTER_VERSION
          flutter config --enable-web
          
      - name: Get Flutter packages
        script: |
          cd mebelplace_demo
          flutter packages pub get
          
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
          
      - name: Flutter analyze
        script: |
          cd mebelplace_demo
          flutter analyze --no-fatal-infos
          
      - name: Flutter unit tests
        script: |
          cd mebelplace_demo
          echo "Skipping tests for App Store build"
          
      - name: Build ipa for distribution
        script: |
          cd mebelplace_demo
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=1 \
            --export-options-plist=$CM_BUILD_DIR/mebelplace_demo/export_options.plist
            
      - name: Upload to App Store Connect
        script: |
          app-store-connect upload \
            --ipa mebelplace_demo/build/ios/ipa/mebelplace.ipa \
            --app-id $BUNDLE_ID
            
    artifacts:
      - mebelplace_demo/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      
    publishing:
      app_store_connect:
        auth: integration
        
        submit_to_testflight: true
        beta_groups:
          - "MebelPlace Beta Testers"
          
        submit_to_app_store: false # Измените на true для автоматической отправки в App Store
