name: mebelplace_mobile
description: MebelPlace - приложение для заказа мебели
publish_to: 'none'
version: 2.0.1+21

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # UI
  cupertino_icons: ^1.0.8
  
  # State Management (updated to latest stable)
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  
  # Networking
  dio: ^5.7.0
  http: ^1.2.2
  pretty_dio_logger: ^1.4.0
  
  # WebSocket
  web_socket_channel: ^3.0.1
  socket_io_client: ^2.0.3+1
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.40
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.1
  
  # Auth & Security
  jwt_decoder: ^2.0.1
  crypto: ^3.0.5
  
  # Push notifications
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  flutter_local_notifications: ^18.0.1
  
  # Video
  chewie: ^1.8.5
  
  # Images
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  
  # UI Components
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  lottie: ^3.1.3
  flutter_staggered_grid_view: ^0.7.0
  pull_to_refresh: ^2.0.0
  badges: ^3.1.2
  google_fonts: ^6.2.1
  
  # Routing
  go_router: ^14.6.2
  
  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0
  
  # i18n
  easy_localization: ^3.0.7
  intl: ^0.20.2
  
  # Utils
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  connectivity_plus: ^6.0.5
  package_info_plus: ^8.0.3
  
  # Audio
  audioplayers: ^6.1.0
  record: ^5.2.1
  
  # AR & 3D
  model_viewer_plus: ^1.7.2
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # Maps
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  
  # Real-time Communication
  agora_rtc_engine: ^6.3.0
  
  # WebView
  webview_flutter: ^4.4.2
  
  # Share
  share_plus: ^12.0.0
  
  # Error tracking
  sentry_flutter: ^8.11.0
  
  # Code generation helpers
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  
  # Either for Clean Architecture
  dartz: ^0.10.1
  
  # Social Auth
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  
  # File handling
  file_picker: ^8.1.4
  mime: ^2.0.0
  build_runner: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
    
  # Linting
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0
  
  # Code generation
  json_serializable: ^6.8.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  injectable_generator: ^2.6.2
  drift_dev: ^2.28.3
  
  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.4
  
  # Icons
  flutter_launcher_icons: ^0.14.1

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/translations/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FF7A00"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

dependency_overrides:
  record_linux: ^1.2.1
  record_platform_interface: ^1.4.0
