-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgXgSbslYnlaFQ2tWT
0O86ENr1XqEsMRgvLes5n6FdFeOgCgYIKoZIzj0DAQehRANCAARQEldtPVorpEmi
UdVxt8m/0+FCY1M1OzjNWDGPkwyZ8ZjGD0O8jpKs26RAKYZuJWpdV4guIKhpgBNw
CSZUy1HR
-----END PRIVATE KEY-----