name: mebelplace
description: "MebelPlace - TikTok-style video platform for furniture masters"
publish_to: 'none'

version: 1.0.0+58

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  flutter_screenutil: ^5.9.0
  
  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Video & Media
  video_player: ^2.8.1
  chewie: ^1.7.4
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  
  # Storage & Caching
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.0
  
  # Animations & Effects
  lottie: ^2.7.0
  shimmer: ^3.0.0
  glassmorphism: ^3.0.0
  
  # UI Components
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  flutter_animate: ^4.3.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.1
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Notifications
  # flutter_local_notifications: ^16.3.2
  
  # Socket.IO
  socket_io_client: ^2.0.3+1
  
  # File handling
  path: ^1.8.3
  mime: ^1.0.4
  integration_test:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "логотип_белый_фон.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "логотип.png"