name: CI

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - develop
      - feature/**

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Server Dependencies
        working-directory: ./server
        run: npm ci
        
      - name: Install Client Dependencies
        working-directory: ./client
        run: npm ci
        
      - name: Lint Server
        working-directory: ./server
        run: npm run lint || echo "Lint not configured"
        
      - name: Lint Client
        working-directory: ./client
        run: npm run lint || echo "Lint not configured"
        
      - name: Build Client
        working-directory: ./client
        run: npm run build
        
      - name: Run Tests
        run: echo "Tests will be configured here"

