name: Deploy to VPS

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies (Server)
        working-directory: ./server
        run: npm ci --production
        
      - name: Install dependencies (Client)
        working-directory: ./client
        run: npm ci
        
      - name: Build Client
        working-directory: ./client
        run: npm run build
        env:
          VITE_API_URL: https://mebelplace.com.kz/api/v1
          VITE_WS_URL: wss://mebelplace.com.kz
          
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/mebelplace
            git pull origin main
            chmod +x ./scripts/deploy.sh
            ./scripts/deploy.sh
            
      - name: Notify Deployment Success
        if: success()
        run: echo "Deployment successful!"
        
      - name: Notify Deployment Failure
        if: failure()
        run: echo "Deployment failed!"

